### ISSUE TITLE
Issue when querying users

### ISSUE THREAD

**Issue by brunotoshio** [GetStream/stream-chat-python#124]
Hi, 

Did anything change in the API? I suddenly started receiving something that is not parsable as `int` in the header `x-ratelimit-limit` and thus, causing a parsing issue.

Code to reproduce the error:
```python
from stream_chat import StreamChat

chat = StreamChat(api_key="My API key", api_secret="My API secret")

chat.query_users({})
```

**Comment by ferhatelmas** [comment]
It's related to double headers in edge infrastructure. Deduplication is rolling out.

**Comment by brunotoshio** [comment]
@ferhatelmas Thanks! I can confirm it's fixed for me.

**Comment by ferhatelmas** [comment]
Thanks for the confirmation and sorry for the inconvenience.

https://github.com/GetStream/stream-chat-python/issues/125 will prevent any similar case.
