### ISSUE TITLE
Response code of 500 for "no more pages" seems wrong

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#16]
I'm using version 0.5.0. When querying `messages` or `members` on a channel, you can supply `offset` and `limit` parameters to implement pagination. If you happen to only have 10 users signed up on your channel, and you use "offset" of 50 and `limit` of 50, you get back HTTP status code 500, which seems incorrect, as it's the 2nd page with a scroll of 50. It seems like status code 404 or status code 200 returning an empty array would be more idiomatically correct than "internal server error."

**Comment by tschellenbach** [comment]
that's definitely not how it is intended to function.

@thesyncim ^^

**Comment by Bogdan-D** [comment]
The issue was fixed, closing ticket
