### ISSUE TITLE
createToken(userID) generates an invalid Token

### ISSUE THREAD

**Issue by andrewschenk-linx** [GetStream/stream-chat-python#19]
When creating a new user token, the response contains extra invalid information.

`chat_client = stream_chat.StreamChat(api_key=GET_STREAM_KEY, api_secret=GET_STREAM_SECRET)
                 token = chat_client.create_token(request.user.id)`

Expected response:

"e*******************************************************************************-**********************************YA"

actual response

"b'e*******************************************************************************-**********************************YA'"

**Comment by tbarbugli** [comment]
Thank you for letting us know. Because`create_token(request.user.id)` returns `bytes` calling `str()` or `repr()` on it will include the b'' wrapping.

We're going to fix this on the API client, in the meantime you can workaround this by calling decode() on the token.

```python
token.decode()
```

**Comment by pterk** [comment]
This should be fixed in release 1.2.0
