### ISSUE TITLE
No way to get response headers because _parse_response strips them

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#20]
https://getstream.io/chat/docs/rate_limits/ recommends using the `X-RateLimit-Reset`  to find out "when the current limit will reset (unix timestamp)." Currently this is impossible with `stream-chat-python` because `_parse_response` strips the headers: 
https://github.com/GetStream/stream-chat-python/blob/1.1.0/stream_chat/client.py#L43-L50

1. Please provide a way to retrieve the headers that the docs specify we should respond to
2. Please update the docs to show how to use `stream-chat-python` to honor rate limits

**Comment by pterk** [comment]
@codekiln Thanks for pointing this out. We wil look into this.

**Comment by peterdeme** [comment]
It's in our plan for Q1 2022.

**Comment by peterdeme** [comment]
Implementation: https://github.com/GetStream/stream-chat-python/pull/90

**Comment by peterdeme** [comment]
New PR for implementation: https://github.com/GetStream/stream-chat-python/pull/92
