### ISSUE TITLE
Any way to "set the user" without calling "update users" endpoint?

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#21]
The docs specify that to use the API, one needs to set the user in the client: https://getstream.io/chat/docs/init_and_users/?language=js#setting-the-user

_Note how we are waiting for the setUser API call to be completed before moving forward. You should always make sure to have the user set before making any more calls. All SDKs make this very easy and wait or queue requests until then._

I don't see any method that lets one set the user without hitting the Update Users API endpoint, which suffers from draconian rate limiting at [200ms / request](https://getstream.io/chat/docs/rate_limits/). 

Is there a way to call `setUser` in the Python API at all, like the other APIs (a python example is NOT in the docs)?

**Comment by peterdeme** [comment]
> Is there a way to call setUser in the Python API at all, like the other APIs (a python example is NOT in the docs)?

No.

The reason you don't see it in the examples because it's a frontend call, not a backend call.
