### ISSUE TITLE
1.3.0 breaks verify_webhook (python 3)

### ISSUE THREAD

**Issue by leibowitz** [GetStream/stream-chat-python#27]
Since https://github.com/GetStream/stream-chat-python/commit/e51c4fa186d34a24754c0401db553f0552d9fa46 I receive an error in [`verify_webhook`](https://github.com/GetStream/stream-chat-python/blob/e51c4fa186d34a24754c0401db553f0552d9fa46/stream_chat/client.py#L287-L289):
> TypeError: Unicode-objects must be encoded before hashing

This seems to be related to the removal of [`six.b`](https://six.readthedocs.io/#six.b). 

I'm using python 3.7, but I have no idea what I'm supposed to be doing. This seems to be a breaking change (in a minor release). And the documentation doesn't mention anything about encoding the data prior to calling `verify_webhook`:
https://getstream.io/chat/docs/webhooks/?language=python#verify-events-via-x-signature-and-x-api-key

What am I missing here?

**Comment by leibowitz** [comment]
anyone reading this?

**Comment by ferhatelmas** [comment]
@leibowitz it was wrong according to documentation and now aligned with the documentation. Body parameter expects bytes. 

If you have a snippet to this call, write it and I can help what needs to be changed.

**Comment by leibowitz** [comment]
maybe that was worth mentioning in the [`CHANGELOG`](https://github.com/GetStream/stream-chat-python/blob/97b6d74d6e5360fdac29d33bd8290211eb3ac609/CHANGELOG#L1-L3)

Even if the documentation was correct, and the implementation was wrong, this is a (purposeful) breaking change. A bit of warning or heads up would be nice.

**Comment by ferhatelmas** [comment]
Dependency drop was mentioned but affected could be mentioned too (verify_webhook is the only one). Adding clarification to changelog/release. Thanks for pointing.

**Comment by ferhatelmas** [comment]
Updated, thanks again for your attention.

changelog: https://github.com/GetStream/stream-chat-python/commit/f02a5569bca3438ba7de11c1fe95109fe5d5c446

release: https://github.com/GetStream/stream-chat-python/releases/tag/v1.3.0
