### ISSUE TITLE
Creating a channel with a new user doesn't set a created_at time on the new user. 

### ISSUE THREAD

**Issue by kgabbott** [GetStream/stream-chat-python#32]
If I create a new channel for a non-registered user id, then that user is created without a proper created_at value.

```
> client.channel('livestream', 'test').create('new-user')

{'channel': {'id': 'test',
  'type': 'livestream',
  'cid': 'livestream:test',
  'created_at': '2020-08-19T22:33:42.163578Z',
  'updated_at': '2020-08-19T22:33:42.163579Z',
  'created_by': {'id': 'new-user,
   'role': 'user',
   'banned': False,
   'online': False},
  'frozen': False,
  'config': {'created_at': '2020-08-06T15:35:24.475131Z',
   'updated_at': '2020-08-06T15:35:24.47511Z',
   'name': 'livestream',
   'typing_events': False,
   'read_events': False,
   'connect_events': False,
   'search': False,
   'reactions': False,
   'replies': False,
   'mutes': False,
   'uploads': False,
   'url_enrichment': False,
   'message_retention': 'infinite',
   'max_message_length': 500,
   'automod': 'simple',
   'automod_behavior': 'flag',
   'commands': None}},
 'messages': [],
 'members': [],
 'membership': None,
 'duration': '12.67ms'}


> client.update_users([{'id': 'new-user, 'name': 'Bob'}])

'users': {'new-user': {'id': 'new-user',
   'role': 'user',
   'created_at': '0001-01-01T00:00:00Z',
   'updated_at': '2020-08-19T22:34:23.22199Z',
   'banned': False,
   'online': False,
   'name': 'Bob'}},
 'duration': '6.85ms'}
```

Note, the channel response doesn't even have a created_at value, and the update_users response has a nonsense created_at value.

If I do the update_user call first and then create the channel, then the user will have a proper created_at value in both the user record of the update_users call and in the created_by field of the channel response.

This causes an issue loading channels in the iOS client library, since it gets a decoding error on the missing created_at key.

gz#5431

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5431'>Zendesk ticket #5431</a>:<br><br>A patch to fix this was pushed recently. Can you try again please?

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/5431'>Zendesk ticket #5431</a>:<br><br>Server patch is live. Assuming fixed, closing the ticket.
Please let us know otherwise.

Kind regards,
ferhat.

**Comment by kgabbott** [comment]
I just checked and the issue is resolved. Thanks!
