### ISSUE TITLE
Use f strings 

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-python#45]
since support is 3.6 above, f strings can be leveraged everywhere.

gz#7901

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/7901'>Zendesk ticket #7901</a>:<br><br>Assigning your tickets to you mate ;p

**Comment by ShreehariVaasishta** [comment]
Can I work on it too?

**Comment by ferhatelmas** [comment]
Sure, go ahead!

**Comment by ferhatelmas** [comment]
#48
