### ISSUE TITLE
Python API Docs?

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#5]
In the [README, you have linked to Official Docs](https://github.com/GetStream/stream-chat-python/blob/d63e323b1cbcf667485ce309800b672572882f41/README.md#documentation), but there are [no python API docs listed at the link, which points here](https://getstream.io/chat/docs/). 

Will you please post some readthedocs-style API docs that are specific to python? For example, how do I use the server side API to bulk upload users while setting the avatar image?

Alternatively, if there are REST API docs, that would be a good in the interim.

**Comment by banagale** [comment]
I had a go at building this. It isn't perfect, but I think this is what we're looking for:

https://stream-chat-python-docs.readthedocs.io/en/latest/_sources/stream_chat.html

**Comment by peterdeme** [comment]
For now, we'll just maintain https://getstream.io/chat/docs/python/?language=python
Thanks for the suggestion.
