### ISSUE TITLE
`update_channel_type` not working as expected

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#6]
It's possible to invoke the commands that `update_channel_type` uses directly; `self.put("channeltypes/{}".format(channel_type), **settings)` works fine.  But calling `update_channel_type` with any arguments to update the channel results in errors:

![image](https://user-images.githubusercontent.com/140930/61994242-45fe3e00-b046-11e9-924d-67c8054f2a7b.png)
![image](https://user-images.githubusercontent.com/140930/61994246-51516980-b046-11e9-8ddf-3f7395331bb7.png)
![image](https://user-images.githubusercontent.com/140930/61994250-57dfe100-b046-11e9-86e6-a2eb1c21dd30.png)

In addition, it appears that one is unable to remove specific commands from the channel type: 
![image](https://user-images.githubusercontent.com/140930/61994273-dd639100-b046-11e9-97f4-f451527aeda5.png)

I'm using `stream-chat==0.4.3`.

**Comment by tbarbugli** [comment]
this indeed a bug on the Python client, the `update_channel_type` is not handled correctly. @mircea-cosbuc can you add a test and a fix for this?

**Comment by mircea-cosbuc** [comment]
About the direct `PUT` call in the screenshots above, if you're calling `client.put` with positional parameters only, the second parameter represents the query arguments. Your call should work if you do `client.put("channeltypes/livestream_custom", data={"commands": ["ban", "unban"]})`

**Comment by codekiln** [comment]
@mircea-cosbuc thank you for the update, that workaround does work for me: 
![image of pycharm debugger executing `client.put("channeltypes/{}".format('livestream_custom_01'), data={"commands": ["ban", "unban"]})` and showing that `commands` are set to `ban` and `unban`](https://user-images.githubusercontent.com/140930/62295077-49286e00-b43a-11e9-877d-3bef5be81509.png)
