### ISSUE TITLE
Attachment Type - Custom Value

### ISSUE THREAD

**Issue by efenacigiraydh** [GetStream/stream-chat-python#60]
We are using both Python and Flutter SDKs. In Flutter SDK, while uploading files, we can set a custom value ('file' in our case) for attachments `type` field. However, when we try to do the same thing using Python SDK, `type` field is converted to Mime-Type like `application/json` even if we set it to 'file' on `send_file` function. 

```python
channel = streamchat.channel(channel_type, channel_id)
channel.send_file(file_url, file_name, {"id": user_id}, "file") # type is set as file
```
Becomes 

<img width="425" alt="Screenshot 2021-04-09 at 14 12 19" src="https://user-images.githubusercontent.com/78353955/114178311-d923f800-993d-11eb-982a-8cc72c0156e1.png">

Is it possible to set a custom value for the `type` field?

gz#10992

**Comment by peterdeme** [comment]
`content_type` parameter has been added to `send_file` method. Thanks for the patience.
