### ISSUE TITLE
Any way to create channels with different configs without creating a new channel type?

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-python#8]
I know how to create a new channel type and then create a new channel using the new channel type in order to customize the settings of that channel.

I've had a request from a product owner to be able to make an administrative toggle to turn on and off replies in a given channel. Should I solve this by creating two different channel types and making the each channel use the one with replies enabled or the one with replies disabled when instantiating the front end? Is there a better way?

**Comment by tschellenbach** [comment]
That approach works. Alternatively you could set a property on the channel and just hide the UI for replies based on that. If you want to be able to turn this on/off for a certain channel that might be easier. (though a tech savvy user would be able to work around it)

**Comment by codekiln** [comment]
@tschellenbach Will I be able to switch between configs for a given channel on the fly? Will messages be lost?

**Comment by tschellenbach** [comment]
type1:123 is not the same channel as type2:123

so you would effectively start a new channel. that's not viable if you need it to be the same conversation, i would recommend using the extra data set on the param to customize your UI
