### ISSUE TITLE
Sorting message results from a channel query

### ISSUE THREAD

**Issue by davidhousedev** [GetStream/stream-chat-python#9]
I'm attempting to query the messages of a channel, but it is unclear from the documentation how to sort those message results in the python SDK.

Here's some hopefully illustrative code:

```python
channel_instance = Channel(stream_client, 'type', 'id')
response = channel_instance.query(messages={'limit': 5})
```

I would expect that I could supply `'sort': 'created_at'` to the dict supplied to `messages`. For example:

```python
# This doesn't work
channel_instance = Channel(stream_client, 'type', 'id')
response = channel_instance.query(messages={'limit': 5, 'sort': 'created_at'})
```

Is there support for sorting the paginated messages returned from channel queries? If so, is there support for ascending and descending sorting?

**Comment by hungphamvn** [comment]
Hi guys,
Any progress about this issue?
Thanks

**Comment by peterdeme** [comment]
Look for the `sort` parameter in the [documentation](https://getstream.io/chat/docs/rest/#channels-querychannels). Plus examples [here](https://getstream.io/chat/docs/other-rest/query_channels/).

Thanks!
