### ISSUE TITLE
Is partial_update_message there in python api client

### ISSUE THREAD

**Issue by guptaprakhariitr** [GetStream/stream-chat-python#93]
Hi I can find update_message function but can't find any function for partial_update_message.
As per the docs https://getstream.io/chat/docs/react/send_message/?language=python#partial-update
there is partial message update atleast in js client i guess.
Can someone help how can i do the same in python?
@peterdeme @ferhatelmas

**Comment by peterdeme** [comment]
@guptaprakhariitr do you use the latest version? that was added last november, so it's a pretty recent change.

![image](https://user-images.githubusercontent.com/19969687/149549232-5ed1c3fd-1cea-4198-b77a-6d2690a34217.png)
